# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment-1
spec:
  replicas: 3  # Number of Pods
  selector:
    matchLabels:
      app: review-deployement # matches pods labeled this way
  template:
    metadata:
      labels:
        app: review-deployement # label applied to pods created using this deployment
    spec:
      containers:
      - name: review-deployement
        image: review-microservice:1.0.0
        ports:
        - containerPort: 8004
