# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: review-microservice-1-service
spec:
  selector:
    app: review-deployement
  ports:
    - protocol: TCP
      port: 8004   # Cluster IP port
      targetPort: 8004  # The port your Node.js app listens on
  type: ClusterIP  # You can use NodePort or LoadBalancer if you need external access
