# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment-1
spec:
  replicas: 3  # Number of Pods
  selector:
    matchLabels:
      app: cart-deployement # matches pods labeled this way
  template:
    metadata:
      labels:
        app: cart-deployement # label applied to pods created using this deployment
    spec:
      containers:
      - name: cart-deployement
        image: cart-microservice:1.0.0
        ports:
        - containerPort: 8003
