# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart-microservice-1-service
spec:
  selector:
    app: cart-deployement
  ports:
    - protocol: TCP
      port: 8003   # Cluster IP port
      targetPort: 8003  # The port your Node.js app listens on
  type: ClusterIP  # You can use NodePort or LoadBalancer if you need external access
