# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: order-microservice-1-service
spec:
  selector:
    app: order-deployement
  ports:
    - protocol: TCP
      port: 8000   # Cluster IP port
      targetPort: 8000  # The port your Node.js app listens on
  type: ClusterIP  # You can use NodePort or LoadBalancer if you need external access
